### ISSUE TITLE
Mentorship

### ISSUE THREAD

**Issue by bogderp** [SpartaHack/SpartaHackII-iOS#38]
Currently when you fill out the location, description, and subjectm only the description is visible on the tickets page. Either the user needs to be able to view all the info under your tickets or the tickets need to be clickable to see the full details. 

Additionally, it's not useful to just see "Mentorship" as the title of each ticket. Since this is only Mentorship and no longer General, Security of Facilities lets make that the mentorship category e.g. Android.

**Comment by mhammerly** [comment]
#32 chris marked it closed so maybe it's better in a new beta

**Comment by cnmcgrath** [comment]
#32 was an issue for mentors viewing tickets. Or that's how I interpreted it

**Comment by cnmcgrath** [comment]
fixed.
