### ISSUE TITLE
Mentor accepting tickets

### ISSUE THREAD

**Issue by bogderp** [SpartaHack/SpartaHackII-iOS#41]
Have a page to display the contents of the ticket. Should not be clicking on the ticket to accept without knowing the details of the ticket

**Comment by cnmcgrath** [comment]
The description is already shown

**Comment by bogderp** [comment]
Yeah just the description, not the platform or subject. It just displays "Mentorship". It also says user name is blank

**Comment by cnmcgrath** [comment]
fixed
