### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by bogderp** [SpartaHack/SpartaHackII-iOS#42]
When a sponsor hasn't loaded the MSUFCU logo is displayed until it loads. While this is nice for MSUFCU, we should consider a loading icon.

**Comment by cnmcgrath** [comment]
Noah is working on a placeholder. Perhaps the SpartaHack logo?

**Comment by bogderp** [comment]
can you do gifs? I can create a gif of our logo being outlined

**Comment by cnmcgrath** [comment]
I think so

**Comment by cnmcgrath** [comment]
we have a placeholder
