### ISSUE TITLE
Splashscreen

### ISSUE THREAD

**Issue by bogderp** [SpartaHack/SpartaHackII-iOS#44]
need a splash screen other than SpartaHack 2016 on a white background. @cnmcgrath give me dimensions and i can get that to you within the hour

**Comment by cnmcgrath** [comment]
already fixed

**Comment by bogderp** [comment]
Where can I find the image

**Comment by cnmcgrath** [comment]
it's not in the beta, I literally just added it 15min ago

**Comment by bogderp** [comment]
I figured, just want to see it =P
