### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by bogderp** [SpartaHack/SpartaHackII-iOS#45]
Set the width of Warriors to 100% of the screen width, Trainees to 75%, and Partners to 50%. Let the height adjust automatically. This should have all the logos of each category be the same width and get rid of the awkwardly wide ones.

**Comment by cnmcgrath** [comment]
This is going to make logos that are wide very very small

**Comment by bogderp** [comment]
their height will be smaller, the width will be the same as every other logo

**Comment by cnmcgrath** [comment]
Right, but some logos like Sevenpoints are very wide and short and constraining their width would make the height super narrow

**Comment by cnmcgrath** [comment]
There really isn't an issue with companies that have wide and narrow logos, they paid for a position in the list and the height is constrained. That's the best way to do it right now
