### ISSUE TITLE
Mentorship: "Your Tickets" status (e.g. "Open") is center-aligned vertically

### ISSUE THREAD

**Issue by laurenbretz** [SpartaHack/SpartaHackII-iOS#49]
It should be aligned with the title of the ticket because if the ticket description is really long it just hangs awkwardly halfway down the page.

ALSO: The entire ticket is two columns, with the only thing in the second column being the status. This causes the ticket description to truncate awkwardly 80% of the way across the page. Fixing the above should allow you to address this too.

**Comment by mhammerly** [comment]
there is also a vertical gray line that presumably should span the height of the ticket but it doesn't

**Comment by cnmcgrath** [comment]
dividing line and status is constrained to the top
