### ISSUE TITLE
Sponsors: remove the "Sponsored by..." line if Nan

### ISSUE THREAD

**Issue by laurenbretz** [SpartaHack/SpartaHackII-iOS#58]
Because we want to highlight the ones that are offered by sponsors, so we shouldn't display that line if it's just a prize we're giving.

**Comment by cnmcgrath** [comment]
Why not "From Spartahack"?

**Comment by laurenbretz** [comment]
I'd be open to discussing this point more, but I am of the opinion that we want to emphasize sponsor prizes, and it is already clear that if it's not sponsored then it is awarded by us.

**Comment by cnmcgrath** [comment]
Prizes are now sponsored by isPrizeSponsored (no sponsor assumes it's a SpartaHack prize) then the name of the sponsor, then the name of the prize if no sponsor. 
![simulator screen shot feb 15 2016 2 24 36 pm](https://cloud.githubusercontent.com/assets/3112711/13058233/dfb0e728-d3ef-11e5-8b5e-a90de3eb3298.png)
