### ISSUE TITLE
Checkin utility

### ISSUE THREAD

**Issue by bogderp** [SpartaHack/SpartaHackII-iOS#61]
Check in utility does not display the name of the attendee. this is no longer in the application. it is now in the user Class. firstName and lastName

**Comment by cnmcgrath** [comment]
relational queries aren't that hard, stop changing the model please

**Comment by bogderp** [comment]
we decided on this weeks ago, see slack

**Comment by bogderp** [comment]
I misspoke, see February 11th

**Comment by cnmcgrath** [comment]
still a weak reason, but I'll fix it

**Comment by cnmcgrath** [comment]
Fixed.
