### ISSUE TITLE
Location and subject overflow

### ISSUE THREAD

**Issue by bogderp** [SpartaHack/SpartaHackII-iOS#62]
lets limit location to 15 characters and subject to 60

![slack for ios upload](https://cloud.githubusercontent.com/assets/9342394/13060899/a0cdbffa-d402-11e5-9842-fdc5876ed582.jpg)

**Comment by bogderp** [comment]
![img_0599](https://cloud.githubusercontent.com/assets/9342394/13060941/ddae2310-d402-11e5-8b79-3258785b3b65.PNG)

**Comment by cnmcgrath** [comment]
fixed
